{"uid":"aa5389d8c0f98fd2","name":"test_change_country_not_found_or_forbidden[authorize_partner-100-403]","fullName":"tests.orders.test_group_order_change_country#test_change_country_not_found_or_forbidden","historyId":"3c314f4e8b9cc7c1ed80c11770dc1379","time":{"start":1744369563567,"stop":1744369564024,"duration":457},"description":"Негативные тесты: изменение несуществующего заказа или без прав","descriptionHtml":"<p>Негативные тесты: изменение несуществующего заказа или без прав</p>\n","status":"skipped","statusMessage":"XFAIL https://ru.yougile.com/team/01c2a92f1328/#IT-507\n\nAssertionError: Ожидался статус 403, но получен 405","statusTrace":"api_client = <api_tests.utils.api_client.APIClient object at 0x7f3cf968a1d0>\nauthorize_func = <function authorize_partner at 0x7f3cf9b7e480>, int_id = 100\nexpected_status = 403\n\n    @pytest.mark.xfail(reason = \"https://ru.yougile.com/team/01c2a92f1328/#IT-507\")\n    @pytest.mark.parametrize(\n        \"authorize_func, int_id, expected_status\",\n        [\n            (authorize_client, 99999999, 403),  # Заказ не найден\n            (authorize_partner, 100, 403),  # Нет прав на изменение\n        ],\n    )\n    def test_change_country_not_found_or_forbidden(api_client, authorize_func, int_id, expected_status):\n        \"\"\"Негативные тесты: изменение несуществующего заказа или без прав\"\"\"\n        authorize_func(api_client)\n        payload = {\"int_id\": int_id, \"country_id\": 2}\n        response = api_client.post(\"/orders/group_order/change_country\", json=payload)\n>       assert_response_status_and_error(response, expected_status)\n\napi_tests/tests/orders/test_group_order_change_country.py:50: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = {'error': '', 'status_code': 405}, expected_status = 403\n\n    def assert_response_status_and_error(response, expected_status):\n        actual_status = response[\"status_code\"]\n>       assert actual_status == expected_status, f\"Ожидался статус {expected_status}, но получен {actual_status}\"\nE       AssertionError: Ожидался статус 403, но получен 405\n\napi_tests/utils/asserts.py:39: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"api_client","time":{"start":1744369557217,"stop":1744369557217,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"api_client::0","time":{"start":1744369565091,"stop":1744369565091,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='https://ru.yougile.com/team/01c2a92f1328/#IT-507')"},{"name":"parentSuite","value":"tests.orders"},{"name":"suite","value":"test_group_order_change_country"},{"name":"host","value":"fv-az2169-383"},{"name":"thread","value":"1825-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.orders.test_group_order_change_country"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"authorize_func","value":"<function authorize_partner at 0x7f3cf9b7e480>"},{"name":"expected_status","value":"403"},{"name":"int_id","value":"100"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["@pytest.mark.xfail(reason='https://ru.yougile.com/team/01c2a92f1328/#IT-507')"]},"source":"aa5389d8c0f98fd2.json","parameterValues":["<function authorize_partner at 0x7f3cf9b7e480>","403","100"]}