{"uid":"c4237ecb9632b072","name":"test_create_two_identical_addresses","fullName":"tests.delivery.test_01_save_delivery_address#test_create_two_identical_addresses","historyId":"1f9b8d2ce2fcde4acfbf59346cd93e3e","time":{"start":1744848830946,"stop":1744848831134,"duration":188},"description":"Тест на невозможность создать два полностью одинаковых адреса","descriptionHtml":"<p>Тест на невозможность создать два полностью одинаковых адреса</p>\n","status":"broken","statusMessage":"ValueError: Ошибка авторизации: {'status_code': 502, 'error': '<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body>\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n'}","statusTrace":"api_client = <api_tests.utils.api_client.APIClient object at 0x7f7a50998310>\n\n    def test_create_two_identical_addresses(api_client):\n        \"\"\"Тест на невозможность создать два полностью одинаковых адреса\"\"\"\n>       authorize_client(api_client)\n\napi_tests/tests/delivery/test_01_save_delivery_address.py:90: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \napi_tests/utils/auth.py:17: in authorize_client\n    return authorize_user(api_client, settings.CLIENT_ACCESS_PARAMETER, settings.CLIENT_PASSWORD)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\napi_client = <api_tests.utils.api_client.APIClient object at 0x7f7a50998310>\naccess_parameter = '1796', password = '123123'\n\n    def authorize_user(api_client, access_parameter, password) -> Response:\n        \"\"\"Авторизация пользователя (клиента, партнера, админа).\"\"\"\n        response = api_client.post(\"/auth\", json={\"access_parameter\": access_parameter, \"password\": password})\n    \n        if \"access_token\" in response:\n            token = response[\"access_token\"][\"token\"]\n            api_client.set_auth_token(token)\n        else:\n>           raise ValueError(f\"Ошибка авторизации: {response}\")\nE           ValueError: Ошибка авторизации: {'status_code': 502, 'error': '<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body>\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n'}\n\napi_tests/utils/auth.py:12: ValueError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"api_client","time":{"start":1744848801662,"stop":1744848801662,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"api_client::0","time":{"start":1744848831138,"stop":1744848831138,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"parentSuite","value":"tests.delivery"},{"name":"suite","value":"test_01_save_delivery_address"},{"name":"host","value":"fv-az1919-435"},{"name":"thread","value":"1933-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.delivery.test_01_save_delivery_address"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"c4237ecb9632b072.json","parameterValues":[]}